### ISSUE TITLE
Can ping but not discovered by HA, no webserver

### ISSUE THREAD

**Issue by wpeterw** [Flamingo-tech/Open-AIR#8]
Just installed my Openair Mini. It connects to my wifi and I can ping the ip address but it's not discovered by HA and no webserver on port 80, any ideas ?

`❯ sudo nmap -sT 192.168.1.202
Starting Nmap 7.80 ( https://nmap.org ) at 2024-03-30 12:51 CET
Nmap scan report for 192.168.1.202
Host is up (0.011s latency).
All 1000 scanned ports on 192.168.1.202 are closed`

**Comment by thomasvnl** [comment]
Did you use your own custom ESPHome config? If so, can you post it here (without any secrets)?

**Comment by wpeterw** [comment]
RH sensor was connected to the wrong header, so the device was in a bootloop.
